name: twilio_dart
version: 0.0.6
author: Marcos Placona <hi@placona.co.uk>
description: An implementation of the Twilio API for Dart.
homepage: http://mplacona.github.io/twilio-dart
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
  http: ^0.12.0+1
dev_dependencies:
  mockito: any
  test: any
